version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: simplecommerce-db
    restart: unless-stopped
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-simplecommerce_mdm}
      POSTGRES_USER: ${POSTGRES_USER:-simplecommerce}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    
    ports:
      - "5432:5432"
    
    # Memory limits for 1GB droplet
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-simplecommerce} -d ${POSTGRES_DB:-simplecommerce_mdm}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simplecommerce-app
    restart: unless-stopped
    
    depends_on:
      postgres:
        condition: service_healthy
    
    environment:
      # Database connection
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-simplecommerce_mdm}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-simplecommerce}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      
      # Google OAuth2 Configuration
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      
      # Email Configuration (Brevo)
      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_SENDER_EMAIL: ${BREVO_SENDER_EMAIL:-noreply@simplecommerce.com}
      BREVO_SENDER_NAME: ${BREVO_SENDER_NAME:-SimpleCommerce}
      
      # Cloudinary Configuration
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      
      # Spring Profile
      SPRING_PROFILES_ACTIVE: digitalocean
      
      # Port
      PORT: 8080
    
    ports:
      - "8080:8080"
    
    # Memory limits for 1GB droplet (app gets most memory)
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    
    # Volumes for logs and temp files
    volumes:
      - app_logs:/app/logs
      - app_temp:/tmp

  # Nginx Reverse Proxy (Optional - for SSL and load balancing)
  nginx:
    image: nginx:alpine
    container_name: simplecommerce-nginx
    restart: unless-stopped
    
    depends_on:
      app:
        condition: service_healthy
    
    ports:
      - "80:80"
      - "443:443"
    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    
    # Minimal memory for nginx
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local
  app_temp:
    driver: local
  nginx_logs:
    driver: local

networks:
  default:
    driver: bridge
