version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: docker.io/postgres:16-alpine
    container_name: simplecommerce-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: nammai
      POSTGRES_PASSWORD: ***REMOVED***
      POSTGRES_DB: simplecommerce_mdm
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - simplecommerce_data:/var/lib/postgresql/data:Z
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:Z
    networks:
      - simplecommerce-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nammai -d simplecommerce_mdm"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application
  api:
    build:
      context: .
      dockerfile: Containerfile
      target: runtime
    container_name: ${COMPOSE_PROJECT_NAME}-api
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/simplecommerce_mdm
      - SPRING_DATASOURCE_USERNAME=nammai
      - SPRING_DATASOURCE_PASSWORD=***REMOVED***
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - app_logs:/app/logs:Z
    networks:
      - simplecommerce-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis (for caching and sessions)
  redis:
    image: docker.io/redis:7-alpine
    container_name: simplecommerce-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data:Z
    networks:
      - simplecommerce-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin (Database Management Tool)
  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    container_name: simplecommerce-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin:Z
    networks:
      - simplecommerce-network

volumes:
  simplecommerce_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
  app_logs:
    driver: local

networks:
  simplecommerce-network:
    driver: bridge 