[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Resource limits for 1GB RAM / 1 vCPU Railway plan
[deploy.resources]
# Railway will automatically set these based on plan
# memory = "1024Mi"
# cpu = "1000m"

# Ultra-optimized JVM for 1GB RAM with minimal lag
[build.env]
JAVA_OPTS = "-Xmx512m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:MaxRAMPercentage=50.0 -XX:+DisableExplicitGC -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -XX:+UseFastAccessorMethods"
