[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Resource limits for 1GB RAM / 1 vCPU Railway plan
[deploy.resources]
# Railway will automatically set these based on plan
# memory = "1024Mi"
# cpu = "1000m"

# JVM optimization for 1GB RAM
[build.env]
JAVA_OPTS = "-Xmx768m -Xms256m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:MaxRAMPercentage=75.0"
