[build]
builder = "nixpacks"

[deploy]
startCommand = "java -Xmx200m -Xms100m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -jar target/simplecommerce-mdm-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
SPRING_PROFILES_ACTIVE = "railway"
