#!/bin/bash

echo "🚀 RAILWAY ULTRA-OPTIMIZED PERFORMANCE TEST"
echo "============================================="
echo ""
echo "📊 Configuration: 1GB RAM / 1 vCPU"
echo "🎯 Target: Memory < 800MB, Lag < 100ms"
echo ""

# Set optimized environment variables
export SPRING_PROFILES_ACTIVE=railway-optimized
export JAVA_OPTS="-Xmx512m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat -XX:MaxRAMPercentage=50.0"

echo "✅ Environment variables set:"
echo "   - JVM Heap: Max 512MB, Initial 128MB"
echo "   - Profile: railway-optimized"
echo "   - GC: G1GC with 100ms max pause"
echo ""

echo "🧪 Performance Test Commands:"
echo "============================="
echo ""
echo "1️⃣ Memory Usage Monitoring:"
echo "   - Check JVM memory: jcmd \$(pgrep java) VM.info"
echo "   - Monitor heap: jcmd \$(pgrep java) GC.heap_info"
echo "   - GC stats: jcmd \$(pgrep java) GC.run_finalization"
echo ""
echo "2️⃣ API Response Time Test:"
echo "   - Health check: time curl http://localhost:8080/actuator/health"
echo "   - Business config: time curl http://localhost:8080/api/v1/admin/business-config"
echo "   - Login API: time curl -X POST http://localhost:8080/api/v1/auth/login"
echo ""
echo "3️⃣ Database Performance:"
echo "   - Connection pool status: Check HikariCP logs"
echo "   - Query performance: Monitor Hibernate logs"
echo ""
echo "🎯 Expected Results:"
echo "   - Startup time: < 2 minutes"
echo "   - Memory usage: < 800MB"
echo "   - API response: < 100ms"
echo "   - Database connections: Max 2"
echo ""
echo "💡 To start with optimized config:"
echo "   mvn spring-boot:run -Dspring.profiles.active=railway-optimized"
echo ""
echo "🚂 For Railway deployment:"
echo "   - Use application-railway-optimized.yml"
echo "   - Set SPRING_PROFILES_ACTIVE=railway-optimized"
echo "   - Copy variables from railway-optimized.env"
