spring:
  datasource:
    url: ${PROD_DB_URL:jdbc:postgresql://localhost:5432/simplecommerce_mdm_prod}
    username: ${PROD_DB_USER:simplecommerce_user}
    password: ${PROD_DB_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none # Không bao giờ tự động thay đổi schema ở production
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  h2:
    console:
      enabled: false

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: native

logging:
  level:
    root: WARN
    com.simplecommerce_mdm: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE_PATH:/app/logs/simplecommerce-mdm.log}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Security configurations for production
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:changeme_in_production}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds
    accessKey: ${JWT_ACCESS_KEY}
    refreshKey: ${JWT_REFRESH_KEY}

# Brevo Email Service Configuration
brevo:
  api-key: ${BREVO_API_KEY}
  sender:
    email: no-reply@simplecommerce.com # Production sender email
    name: SimpleCommerce MDM 