# ==============================================
# Development Configuration - SECURE VERSION
# All sensitive data moved to environment variables
# ==============================================
spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:simplecommerce_mdm}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        default_schema: public
        jdbc:
          time_zone: UTC+07:00

  # OAuth2 Configuration - SECURE: Using environment variables only
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

logging:
  level:
    root: INFO
    com.simplecommerce_mdm: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger Configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: true

# OpenAPI Configuration
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Simplecommerce MDM API
    version: 1.0.0
    description: API documentation for Simplecommerce MDM

# Frontend Configuration
frontend:
  url: ${FRONTEND_URL:http://localhost:5173}
  admin-seller:
    url: ${FRONTEND_ADMIN_SELLER_URL:http://localhost:3000}
  user:
    url: ${FRONTEND_USER_URL:http://localhost:3001}

# JWT Configuration - SECURE: Using environment variables only
jwt:
  expiryMinutes: 60
  expiryDay: 14
  accessKey: ${JWT_ACCESS_KEY}
  refreshKey: ${JWT_REFRESH_KEY}

# Brevo Email Service Configuration - SECURE: Using environment variables only
brevo:
  api-key: ${BREVO_API_KEY}
  sender:
    email: ${BREVO_SENDER_EMAIL:mnam3239@gmail.com}
    name: ${BREVO_SENDER_NAME:SimpleCommerce MDM (Dev)}

# Cloudinary configuration - SECURE: Using environment variables only
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}